export { ApolloCache, ApolloClient, Cache, CombinedGraphQLErrors, CombinedProtocolErrors, DataState, DataValue, DefaultContext, DocumentNode, ErrorLike, ErrorPolicy, FetchPolicy, GetDataState, gql, InMemoryCache, LinkError, MissingFieldError, NetworkStatus, NormalizedCache, NormalizedCacheObject, OperationVariables, Reference, RefetchOn, Scalar, ServerError, ServerParseError, StoreObject, TypedDocumentNode, UnconventionalError, UpdateQueryOptions } from '@apollo/client';
export { isErrorLike, LocalStateError, toErrorLike } from '@apollo/client/errors';
export type { MissingTree } from '@apollo/client/cache';
export type { DeepPartial } from '@apollo/client/utilities';
export { Apollo } from './apollo';
export { ApolloCacheEx, CacheQueryCompleteResult, CacheQueryData, CacheQueryFn, CacheQueryIncompleteResult, CacheQueryOptions, CacheQueryResult } from './cacheEx';
export { CacheQueryObservable, IncompleteCacheError } from './cacheQueryObservable';
export { APOLLO_CLIENT_FACTORY, ApolloClientFactory } from './clientFactory';
export * from './gql';
export { ApolloRegistry as ɵApolloRegistry } from './internal/apolloRegistry';
export { APOLLO_INSTANCE_FACTORY as ɵAPOLLO_INSTANCE_FACTORY, ApolloInstanceFactory as ɵApolloInstanceFactory } from './internal/instanceFactory';
export * from './map';
export * from './operators';
export { ApolloOrbitFeature, provideApollo, provideApolloInstance, withApolloOptions } from './providers';
export { QueryObservable } from './queryObservable';
export * from './signals';
export { APOLLO_MULTI_ROOT } from './tokens';
export * from './types';
